#pragma once

#define CAN_MOUSE_BUTTON_1         0
#define CAN_MOUSE_BUTTON_2         1
#define CAN_MOUSE_BUTTON_3         2
#define CAN_MOUSE_BUTTON_4         3
#define CAN_MOUSE_BUTTON_5         4
#define CAN_MOUSE_BUTTON_6         5
#define CAN_MOUSE_BUTTON_7         6
#define CAN_MOUSE_BUTTON_8         7
#define CAN_MOUSE_BUTTON_LAST      CAN_MOUSE_BUTTON_8
#define CAN_MOUSE_BUTTON_LEFT      CAN_MOUSE_BUTTON_1
#define CAN_MOUSE_BUTTON_RIGHT     CAN_MOUSE_BUTTON_2
#define CAN_MOUSE_BUTTON_MIDDLE    CAN_MOUSE_BUTTON_3